version: '3.3'
services:
  db:
    build: ./db_mysql
    command: --default-authentication-plugin=mysql_native_password
  send-uuid:
    build: ./send-uuid
    volumes:
      - /home/saify2j/Desktop/angel-projects/send-uuid/send-uuid/:/usr/src/app
    ports:
     - 6001-6005:8080
    depends_on:
     - db
    environment:
     - WAIT_HOSTS= db:3306
     - WAIT_HOSTS_TIMEOUT=100
     - WAIT_BEFORE_HOSTS= 10
     - DATABASE_HOST=db

  redis-server:
    image: 'redis'
