version: '3'
services:
  send-uuid:
    build: ./send-uuid
    ports:
     - 6001:8080
     - 6002:8080
    depends_on:
     - db
    environment:
     - DATABASE_HOST=db
  db:
    build: ./db_mysql
    command: --default-authentication-plugin=mysql_native_password
  redis-server:
    image: 'redis'